### ISSUE TITLE
Correct background color styling

### ISSUE THREAD

**Issue by jpshackelford** [jpshackelford/jpshackelford-blog#2]
The new site is attempting to look like https://jpshackelford.info in light mode. But I really don't understand css variables which are heavily used in Pico.css so my changes in [jps.css](https://github.com/jpshackelford/jpshackelford-blog/blob/main/static/css/jps.css#L8) is coloring all containers with a background color instead of just the background area of the blog itself.

![old](https://github.com/jpshackelford/jpshackelford-blog/assets/13136/c83c1955-77a4-4563-a2df-98ffdb89e0ae)
![new](https://github.com/jpshackelford/jpshackelford-blog/assets/13136/5e588840-dce2-44c2-8b5c-ebc2d26dd26a)

Using an approach like the below works but I don't really know how to make that work with the css variables and the light mode / dark mode stuff that pico implements.
```
body { background-color: #c0b5a8 } 
```

See:
- https://picocss.com/docs/customization.html
- https://picocss.com/docs/themes.html
- https://github.com/picocss/pico/blob/master/css/themes/default.css

I'd really like a solution that is clean and respectful of the Pico way doing things.

**Comment by usphantomlancer** [comment]
Done. Ruslan.
https://github.com/jpshackelford/jpshackelford-blog/pull/5
